### ISSUE TITLE
fix odd disposition name for Textiles "recyclingGeneric <LC>"

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#10]
Not urgent, just reporting this in case it indicates that something is messed up on a systemic level in Gabi.

Gabi's exports, both the Excel and CSV versions, have some quirks.  For example some of the output field/category names have the mark LC in angle brackets concatenated to them.  That's been fine, because it's consistent enough that I can ignore or eliminate it.

However for one material and disposition the LC thing stands out.  For textiles the recyclingGeneric disposition has the LC appended while none of the other dispositions or factors have it.  This is in both the Excel and CSV exports.

![image](https://user-images.githubusercontent.com/49459721/107679758-cfd62200-6c51-11eb-9c49-80fbe12631ed.png)

Might be worth looking into?  For the time being I have dealt with it in code.

**Comment by DEQmbrown2** [comment]
ok, now this really weird.  github isn't showing all of my message about the control codes!  might be messing with the fact that the github site itself uses markdown for these conversation threads.  anyway if you look at the screenshot above you will see the problem... the letter LC inside angle brackets.

**Comment by DEQpcanepa** [comment]
Some sort of odd vestige of a previous version.  Fixed.
![Capture](https://user-images.githubusercontent.com/77121595/111385562-3a6ee900-8668-11eb-81f6-fafb111b4dd1.PNG)

**Comment by DEQmbrown2** [comment]
Cool!  I really like this issue system.
