### ISSUE TITLE
rename recycling dispositions so that recyclingGeneric represents embodied burden paradigm

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#18]
Peter C, i am wondering if Gabi recycling dispositions should be renamed so that the moniker "recyclingGeneric" (which we've been using) reflects the embodied burden paradigm.  and any other name reflects a specific type of recycling.  don't do yet, but let's talk about it.

**Comment by DEQpcanepa** [comment]
Yes completely possible to do a find/replace to make the nomenclature more specific regarding the recycling allocation approach.  We do also cover this in the background/technical documentation.  Glad to discuss.

**Comment by DEQmbrown2** [comment]
note to myself: i can check if this one is done simply by reviewing the updated impact factors.

**Comment by DEQmbrown2** [comment]
looks like this is done.  closing issue.
