### ISSUE TITLE
improve/extend the "short list" of impact categories

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#24]
@DEQpcanepa , Here's a valid issue that Chris K. brought up.  My own programming is at fault, but I need your input to fix it.  

We present WIC as a general-use tool, where users can choose to apply any of the diverse impact categories available in your Gabi output.  However, until now I have filtered the list of impact categories down to the 9 or 10 that we in materials management might actually use.  This is convenient for us but doesn't necessarily fit the needs of other users.

I've attached the file I use to process/correct impact category names.  It has a column called "shortList" where entries of TRUE will cause impact factors in that category to be saved in the official WIC publication. (In addition, to respond to another of Chris' comments, a long version of the impactCategory name is now saved, so that interested users can get Gabi's full label for the category.)

I have a feeling that we should expand the published list of categories, but I don't know how much you think is appropriate.  My guess is we (or you, really) should mark as TRUE as many as you think could really be meaningful for our users.
[impactCategoryPickerFixer.xlsx](https://github.com/OR-Dept-Environmental-Quality/wic-base/files/5990773/impactCategoryPickerFixer.xlsx).

Another alternative: we could just publish them all, and then provide a "recommended" list to users who don't really know what to pick.

Let me know what you think, and if relevant, send me back an updated spreadsheet.  Thanks! martin

**Comment by DEQpcanepa** [comment]
Hi Martin - I went through the list and changed an additional 8 indicators to TRUE.  It's probably worth noting that this list is an already curated list from the total available in GaBi, reflecting the most common impact categories reported in LCA.  I couldn't find an easy way to visually show you which ones I added, but since column G "impactCategory" is blank next to them, you should be able to ID them out.  Just in case, below are the rows that I suggested adding.

[impactCategoryPickerFixer (PC).xlsx](https://github.com/OR-Dept-Environmental-Quality/wic-base/files/6152318/impactCategoryPickerFixer.PC.xlsx)


Rows added - 23, 25, 29, 30, 35, 49, 50, 51

One other thing that strikes me, is that we should be sure to include the corporateSource (e.g. TRACI 2.1) in the name of the impact categories.  Or at least make it easy to deduce that (footnote, pop-up comment, documentation, etc...)

**Comment by DEQmbrown2** [comment]
Looks good!  Now that I have your fixes, I will reassign this issue to me and fix the entries in the official repository file.

Regarding corporateSource, a few questions for you:

* should I change the name of that field? Is there a more traditional piece of LCA vocabulary to use for that?
* I certainly can include it in the official (long) name of the impact category.  I can put it in square brackets or something like that, or I can use it as a prefix.
* For the ones provided by GaBi, do you have a suggested entry for that field?  ("GaBi"? "GaBi internal"?)

Thanks!

**Comment by DEQpcanepa** [comment]
Responses to questions on corporateSource:

- usually this is referred to impact assessment method, so perhaps we could call this impactAssessmentMethodSource
- not required, as long as there is someway to trace the short names back to the full names.  I'll defer to you here regarding how, should the long names be included, this will effect the visualization of results
- in GaBi, they're called "quantities," which is a bit of a misnomer.  But you could call them gabiQuantityName or gabiImpactCategoryName.

**Comment by DEQmbrown2** [comment]
Thanks! I will make those changes.  I kind of getting a good feeling from closing the issue and then moving it to the Done column in the kanban.

**Comment by DEQmbrown2** [comment]
followup for the record:

* I didn't change "corporateSource" to "impactAssessmentMethodSource" even though the latter made more sense.  Chris K approved my document where the field name corporateSource appears, so I just stuck with it.
* the long names are part of the impactFactors file, so they are always available to the user of that file.  For WIC expressions designed for nonprogrammers (e.g. the web app) we may need to do something better.
* I will see if I can expressly label the GaBi "quantities", still working on it
