### ISSUE TITLE
discuss: provide explanations of impact categories in Impact Modelling doc?

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#28]
For discussion:

Both Chris K. and test users have asked follow up questions about the impact category names -- the short names I was using  
(e.g. "GWP 100") were good for charts, but not sufficiently detailed for technical folks.  

I have done several things so far.  I have changed the impact factors input so that the imported file includes, short names ("GWP 100"), LCIA method (e.g. TRACI) and longer names with more explanation, straight from the GaBi output (e.g. "Global warming without land use change blah blah blah").

Open question: is this sufficient? Do we need to do any listing or explanation of impact categories?  We will definitely need to explain our biogenic categories, but is more necessary?

This is sort of related to issue #24 .

**Comment by DEQpcanepa** [comment]
This seems sufficient to me.  In fact, prior to reading this I suggested the inclusion of the "corporateSource" name for clarity in issue #24.  But if you've included that along with the full GaBi names, that should do it.

Additionally, the background documentation will provide more details, specifically "impact modeling for the WIC."

**Comment by DEQmbrown2** [comment]
looks like this was taken care of, between text in the impact modeling document, and the addition of the long category names in the import
