### ISSUE TITLE
gather documents from technical review for inclusion in release

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#31]
@DEQpcanepa , i'm assigning this to myself, but might need some help figuring out which docs to include.

* the technical review statement from Sphera, obviously
* the spreadsheet with comments?
* earlier drafts of stuff?
* also need to clarify the status of the legendary document "Impact Modeling for the Waste Impact Calculator"

**Comment by DEQpcanepa** [comment]
Working on a few tweaks to the "Impact Modeling for the WIC" document, post review.  Will put it in the documentation folder, along with the review materials, later this week.

\\deqhq1\swrshare\!PROGRAMS-SOLID-WASTE-(PSW)\LCA\Projects\WIC\Documentation
