### ISSUE TITLE
get introduced to Semantic Versioning

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#32]
@DEQpcanepa , since we are going to be releasing WIC with version numbers, I thought we should review current "best practices" for creating version numbers, especially in a millieu where other people are going to be using our software/data files.   Once you read this message, you can mark this issue as done! 

First, **you don't need to number any Gabi files or files you give me with official version numbers**.  You can keep using dates or other things like that.  It's the **whole collection of material** that gets a release number on github, not the individual files.

But you should know the conventions that are behind the version numbers, because they help others understand how to use our work, and how we might want to think about our revisions.

To write the release numbers, we can follow this standard (it's not too long): https://semver.org/spec/v2.0.0.html .  The summary:

![image](https://user-images.githubusercontent.com/49459721/122619397-35457f80-d045-11eb-9704-df06ec70f16e.png)

For us, the "public API" will just be our documentation, so don't worry about that.  Currently we're in the anything-goes "zero" release stage, where anything can change.  But once we get to a full expression of what Chris K reviewed, it'll be version 1.0.0, and we will need to be a little more forma..

The MAJOR.MINOR.PATCH distinction is based on backwards compatibility.  I imagine most of the changes you'll be making in the future will be corrected impact factors (I think that would count as a PATCH, e.g. 1.0.1), or adding new materials/dispositions (that'd be MINOR, like 1.1.0).   We can write a public release note (as short or long as we like) with each release, so users know basically what happened.  (E.g. for release 1.1.0 the release note might be "added pyrolisis as a recycling disposition, made other bug fixes").  

PATCH and MINOR releases are supposed to be backward compatible.  So if someone has developed code based on 1.0, it should still work for 1.1.

The MAJOR version number only changes if something structural about the project changes in a way that is inconsistent with previous conventions and might mess up someone else's code (for example, if we changed the structure of data files).  I doubt we'll be doing that --- maybe ever?

The other key highlight is this:

![image](https://user-images.githubusercontent.com/49459721/122620569-23191080-d048-11eb-81bb-78aa57f4cf48.png)

Once we do a release, the release shouldn't change.  Version 1.0.0 should always have the same files in exactly the same versions. When we inevitably decide we need to correct something, the new set of files will be 1.0.1 or whatever.  The idea is that each release is self-sufficient at the time it is published, and any revisions are part of a public history.  

Anyway, I will handle most of this via github.  But the upshot for you is -- keep me up to date, and especially let me know if your revisions are gradual fixes and improvements (most likely) or revolutionary.

Thanks!

**Comment by DEQpcanepa** [comment]
This all makes sense.
