### ISSUE TITLE
decide on what review-related documentation to include

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#36]
@DEQpcanepa , I'm not sure how much Chris K. wanted us to publish from his tech review.  I've already included his final review statement in the wic base [documentation folder](https://github.com/OR-Dept-Environmental-Quality/wic-base/tree/main/documentation).  Did he want more?  

The only detail I recall was that he wanted us to justify the different treatments of biogenic carbon that we based on the Oregon forest carbon inventory.  Looks like the "impact-modeling-for-the-wic" document includes that -- but the version I have is old.

**Comment by DEQmbrown2** [comment]
oops, this is a duplicate of issue #31 , so i am deleting that old one.

**Comment by DEQpcanepa** [comment]
Hi Martin - I think we should include the following items from Chris' review:

- the technical review statement (statement-of-independent-technical-reviewer.pdf)
- the spreadsheet with comments (WIC-technical-review-comments-final-2021-06-03.xlsx) 

I've placed these files in the folder below.  

\\deqhq1\swrshare\!PROGRAMS-SOLID-WASTE-(PSW)\LCA\Projects\WIC\Documentation\2021-06-final

Additionally, I've made minor updates to the impact modeling documentation and placed it in the same folder, as noted in #31

**Comment by DEQmbrown2** [comment]
ok, added updated files to official repository. closing ticket.
