### ISSUE TITLE
find and incorporate revised "impact modeling" doc

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#37]
@DEQpcanepa , I apologize I cannot find the recent revision of "impact modeling for the waste impact calculator."  The copy I have looks like it is from April 4, 2021.

**Comment by DEQpcanepa** [comment]
Hi Martin - I've placed copies of all the latest documentation (from me) in the folder below.

\\deqhq1\swrshare\!PROGRAMS-SOLID-WASTE-(PSW)\LCA\Projects\WIC\Documentation\2021-06-final

There are two files:

1. impact-modeling-for-the-wic-2021-07-01.docx - describes the underlying life cycle inventory and modeling approach for the WIC.
2. Appendix A - WasteImpactCalculatorMasterDataList.xlsx - enumerates the specific data sources used to develop the life cycle inventory  model for the WIC.
