### ISSUE TITLE
fix GaBi's export of a disposition "recyclingToContainer <LC>"

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#40]
@DEQpcanepa , this isn't urgent, as it's easy for me to fix in code.

But for some reason GaBi's export calls appends " <LC>" to the disposition name "recyclingToContainer".  See screenshot below

![image](https://user-images.githubusercontent.com/49459721/123330226-9ca27a00-d4f2-11eb-885a-91d031dec54a.png)

**Comment by DEQpcanepa** [comment]
Hi Martin - I was able to change the nomenclature for this one factor, not sure how I missed this but must have made a change to the model which resulted in the software adding this suffix.  Anyhow, the emission factor exports should report without the "< LC >" now.  I'm in the process of rerunning the impact factor results and will place them on the server below, upon completion (this afternoon), in a subfolder with today's date.

\\deqhq1\swrshare\!PROGRAMS-SOLID-WASTE-(PSW)\LCA\Projects\WIC\Emissions Factors

**Comment by DEQmbrown2** [comment]
cool, I will import them soon.
