### ISSUE TITLE
add reuseLumber as a disposition for wood

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#55]
@DEQpcanepa , this may be a fairly large request, so feel free to let me know about how realistic it is. 

I'd like to add reuse of lumber as a disposition for wood for several reasons.

* In September, Jordan wants to apply WIC in built-environment end-of-life stuff, and while WIC doesn't have concrete or asphalt pavement, we do have wood.  As I read in your Impact Modeling document, "wood" in WIC is mostly lumber.
* I've recently done a pretty exhaustive conceptual study of prospects for reuse (read the fantastic memo! \\deqhq1\swrshare\!PROGRAMS-SOLID-WASTE-(PSW)\Materials Management Goals and Measures\misc\reuse and repair\memo 20210726\memoTheCaseAgainstDoingReuseOnFaith20210726.pdf)  and, while it was discouraging, I came away thinking that lumber was one of the few clear good cases for reuse.

I can't recall if you have modeled reuse of lumber before.  I know Andey Nunes put together a compilation of factors that he used in his work (and I adopted for my little study of the Heartwood building resource store) but that was only in terms of GHGs and energy.  It didn't yield the generous palette of results that WIC does. :)

Let me know how you feel about this and what sort of workload/timeline could be involved.  Cheers, Martin

**Comment by DEQpcanepa** [comment]
Hi Martin – I did read it and my initial thought was that it shouldn’t be that difficult, if we follow the same logic of how we model glass.  Basically, some estimate of the impacts of deconstruction/recovery of lumber (e.g. tools, truck transport), an estimate of the losses/yields from the deconstruction/recovery process, and then a credit for the substitution of primary production.  For GWP we’ll need to determine/correct for the carbon stored in the product that remains in it (and potentially for the carbon stored in the forest – e.g. using our slash and EPA FCS factors)

I believe Jordan, Andy, and Simon may have some of this information in their report on demo v. decon, see assumptions.

So really what I would need us data/assumptions on:

•	equipment and tool use (fuels, electricity, consumables, etc…) per unit of wood
•	yield losses (e.g. for every 1 ton of wood in a home, 0.8 tons are suitable for reuse)
•	transport modes/distances for material recovery per unit of wood
•	disposition of wood that is recovered by not suitable for reuse
•	anything unique about biogenic carbon fluxes

I could probably cobble something together this week if we have data on the above, but I’m out again next week out at Wallowa Lake.  So if data/assumptions on the above aren’t available, then I can probably have a draft result towards the end of the month.

Jordan/Martin – I haven’t reviewed the above report, but do you know if it has specifics on the above?
