### ISSUE TITLE
update Technical Overview and Impact modeling documents with wood reuse notes

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#61]

**Comment by DEQmbrown2** [comment]
@DEQpcanepa , thanks for updating wood with those reuse factors.  I want to include those in the 1.1 release.  If you haven't already, please add a paragraph or two to the "Impact Modeling" document to explain how you approached modeling that.  Alterable versions of the WIC documentation files, including the Impact Modeling document, are in this folder: \\deqhq1\swrshare\!PROGRAMS-SOLID-WASTE-(PSW)\LCA\Projects\WIC\Documentation\2021-09 .

I will make suitable changes in the Technical Overview.

**Comment by DEQjpalmeri** [comment]
This is awesome.  Can't wait to comment more!

**Comment by DEQpcanepa** [comment]
Hi Martin - I updated the document "impact-modeling-for-the-wic.docx" with a section on the new factors for Wood_endOfLife_reuseGeneric, in the folder below.  The document was updated using tracked changes, so feel free to review and accept the changes (or modify as you see fit).  Here's what I changed:

- added new section for wood (reuse) in existing wood section
- Updated the ToC
- Updated Table 1 of material and disposition combinations by adding wood_reuseGeneric

\\deqhq1\swrshare\!PROGRAMS-SOLID-WASTE-(PSW)\LCA\Projects\WIC\Documentation\2021-09

I've left the issue open, you can close it if you're satisfied with the content.

**Comment by DEQmbrown2** [comment]
Excellent, thank you.  I will check it out and likely publish it immediately. Any serious reservations, I will let you know-martin

**Comment by DEQmbrown2** [comment]
accepted all the changes and posted to github.  Thanks!
