### ISSUE TITLE
rerun WIC impact factors given new GaBi/ecoinvent updates

### ISSUE THREAD

**Issue by DEQmbrown2** [OR-Dept-Environmental-Quality/wic-base#68]
sometime in April 2023?

**Comment by DEQmbrown2** [comment]
update: @DEQpcanepa , it turns out you re-exported the WIC impact factors back in Sept. 2022 when we were working on RMA material lists.  Given that our previous impact factors were from Sept. 2021, I assume that the Sept. 2022 factors should be based on improved GaBi databases.  Let me ASAP if I SHOULDN'T use these for WIC in general.  I will remove any material names or dispositions that you created especially for RMA.

**Comment by DEQpcanepa** [comment]
I think I can reply directly to these emails and it will update GitHub?!  Fingers crossed.

Feel free to use the 2022 factors, they indeed would represent an update to the underlying GaBi databases.

Peter Canepa
LCA Specialist | Materials Management Program<http://www.oregon.gov/deq/mm/Pages/default.aspx>
Oregon Department of Environmental Quality
700 NE Multnomah St. Suite 600, Portland, OR 97232
O: 503-229-5467 | F: 503-229-6037 | ***@***.******@***.***>

**Comment by DEQmbrown2** [comment]
Yes, that worked - your reply went into the github issue thread (see screenshot below, also note github email addresses in your email client).   Note the github issue thread, though obscure, is part of the public record, so in those rare circumstances where we are dealing with legally protected information, we should communicate it some other way, perhaps DEQ network drives. --martin


***@***.***

**Comment by DEQpcanepa** [comment]
Hello Martin - I've finally gotten to updating the WIC factors based on the background database updates in GaBi.  You'll find the latest factors at the link below.

\\deqhq1\swrshare\!PROGRAMS-SOLID-WASTE-(PSW)\LCA\Projects\WIC\Emissions Factors\20230509<file://deqhq1/swrshare/!PROGRAMS-SOLID-WASTE-(PSW)/LCA/Projects/WIC/Emissions%20Factors/20230509>

Let me know if you have issues or questions.

Sincerely,

Peter Canepa
LCA Specialist | Materials Management Program<http://www.oregon.gov/deq/mm/Pages/default.aspx>
Oregon Department of Environmental Quality
700 NE Multnomah St. Suite 600, Portland, OR 97232
O: 503-229-5467 | F: 503-229-6037 | ***@***.******@***.***>
